[package]
name = "connect_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = 'old'
path = 'old/main.rs'

[[bin]]
name = 'new'
path = 'new/main.rs'


[dependencies]

[profile.release]
debug = true
